#!/bin/env bash

cd /opt/minecraft/

if [ ! -f /opt/minecraft/minecraft_server.jar ]
then
    curl "https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar" -o /opt/minecraft/minecraft_server.jar
fi

if [ ! -f /opt/minecraft/eula.txt ]
then
    echo "eula=true" > /opt/minecraft/eula.txt
fi

exec java -Xmx1024M -Xms512M -jar minecraft_server.jar --nogui
